### ISSUE TITLE
Fast Refresh in Next.js doesn't work

### ISSUE THREAD

**Issue by StarpTech** [markdoc/markdoc#110]
### What happened?

Fast Refresh does not work when using the Next.js plugin. You can reproduce it on your own [docs](https://github.com/markdoc/docs).

### To reproduce

1. Checkout https://github.com/markdoc/docs
2. Start `npm run dev`
3. Go to [http://localhost:3002/docs/getting-started](http://localhost:3002/docs/getting-started)
4. Edit text in `pages/docs/getting-started.md`
5. No effect unless you reload the page.

### Version

0.1.3

### Additional context

@markdoc/next.js": "^0.1.4"

**Comment by mfix-stripe** [comment]
@StarpTech our docs use a slightly different system than a typical Markdoc integration, because we need to demonstrate Markdoc both on the server (typical) and on the client (to showcase the in browser editor)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62121649/176229311-5bd1b417-cdf5-4650-b78b-1c565cbf95fc.png">

Without this custom integration, fast refresh will work. 


What operating system/browser are you using?

**Comment by mrboen94** [comment]
Same happens here, using the new templates from tailwindui and firefox.
It also seems like local images are struggling to be loaded, while remote images work as expected.

**Comment by StarpTech** [comment]
Hi @mfix-stripe, the markdoc docs was just an example. I reproduce it with a simple Next.js example according to the docs. As @mrboen94 mentioned the spinner is visible but the content is load refreshed.

Ubuntu, Chrome

**Comment by mfix-stripe** [comment]
I imagine this could be an Ubuntu specific issue. 

I just cloned our starter repo (https://github.com/markdoc/markdoc-starter), and the Fast Refresh is working on MacOS/Chrome:

https://user-images.githubusercontent.com/62121649/176302297-840fb0cc-2160-42a7-bbd6-e1c549924167.mp4

**Comment by StarpTech** [comment]
The demo works for me too :confused: but doesn't in my app. After upgrading to [0.1.5](https://github.com/markdoc/next.js/releases/tag/0.1.5) it also works in my app. Thank you :partying_face:

**Comment by mfix-stripe** [comment]
Oh awesome! Cool if I close this issue @StarpTech? 🙂
