### ISSUE TITLE
Next.js plugin - Does not contain a default export (imported as 'tags').

### ISSUE THREAD

**Issue by StarpTech** [markdoc/markdoc#111]
### What happened?

I see the following error when building Next.js

```
Attempted import error: '/home/starptech/repositories/test/website/markdoc/tags/index.ts' does not contain a default export (imported as 'tags').
```

markdoc/tags/index.ts
```ts
/* Use this file to export your markdoc tags */
export * from './callout.markdoc'
export * from './cover.markdoc'
export * from './codeblock.markdoc'

```

I use the markdoc Next.js integration

### To reproduce

1. Create a markdoc example with Next.js integration
2. Build the Next.js project.

### Version

0.1.3

### Additional context

"@markdoc/next.js": "^0.1.4",

**Comment by mfix-stripe** [comment]
@StarpTech this error comes from some internal webpack thing, but as far as I can tell, is completely benign. 

Are you seeing issues besides the logged error (outside of #85)

Which _exact_ `@markdoc/next.js` version are you using? I'm also assuming you are still using Ubuntu, Chrome?

**Comment by StarpTech** [comment]
It reports the errors but it works. I use `0.1.4`.

> I'm also assuming you are still using Ubuntu, Chrome?

Yes

**Comment by mfix-stripe** [comment]
@StarpTech I'm going to mark this as closed since not a real bug. We will keep an eye on the warning message reported here in case it causes real issues. Since this is internally reported by webpack/next.js, there isn't too much we can do to mitigate it, as far as I'm aware. 

If you do find a clean way to resolve this issue though, please feel free to share a PR.
