### ISSUE TITLE
Can not build more than 101 pages with Next.js

### ISSUE THREAD

**Issue by kejiweixun** [markdoc/markdoc#250]
### What happened?

I clone markdoc's Next.js [starter demo](https://github.com/markdoc/markdoc-starter), randomly add 97 markdom files to `pages/docs/` folder, then run `npm run build`, and Next.js will stuck on `info  - Creating an optimized production build ...` forever.

### To reproduce

1. `git clone https://github.com/markdoc/markdoc-starter`
2. Add random markdown files to `pages/docs/` folder like below:
```js
const fs = require("fs");
for (let i = 0; i < 98; i++) {
  fs.writeFileSync(`./pages/docs/${i}.md`, `##${i}`);
}
```
3. `npm run build`
4. It will stuck on `info  - Creating an optimized production build ...` forever.
5. Delete one markdown file from `pages/docs/`, and it will build successfully.
6. And then, without deleting `.next` folder, add some more markdown files to `pages/docs/`, will build successfully. But if you delete `.next` before adding more files, it will hang forever.

I try to refactor my blog using markdoc, then found this issue. Had tried several next versions and markdoc versions, no luck. I think it's more likely markdoc related? Looking for help, thanks!

### Version

try latest and older versions

**Comment by kejiweixun** [comment]
I think I know what's wrong now, but don't know how to fix it.

This issue is related to `@markdoc/next.js`. Somehow when having more than certain markdown files, [`await this.importModule()`](https://github.com/markdoc/next.js/blob/569b557c540a8a3bb74b8e04cf91a97f51f90f0a/src/loader.js#L77)` just can't resolve, which cause the forever hang.

**Comment by HonzaMac** [comment]
What does command 'limits' in terminal print?

**Comment by mfix-stripe** [comment]
Cc @ijjk in case you have ideas. I doubt this is a `@markdoc/next.js` bug, but it could be. 

Regardless, I'm sure we could speed up our builds with some sort of caching.

**Comment by mfix-stripe** [comment]
Hey folks, sorry for the delay here. I dug into this deeper, and there is something weird going on within Webpack and/or Next.js that prevents us from importing a module more than a certain amount of times at once. The trouble is we don't know that number ahead of time, nor are we able to stop if from hanging forever without introducing even worse behavior. 

I fixed this issue here (https://github.com/markdoc/next.js/pull/19) by removing the build-time `importModule` call, which disables the [Markdoc validation](https://markdoc.dev/docs/validation) support we had previously included. If you want to validate all your content (for example in `CI`), you should call [`Markdoc.validate`](https://markdoc.dev/docs/validation) in a separate script. 

I will release this fix on Monday.

Full validation was never supported in `@markdoc/next.js` so this shouldn't break any applications. 

As a follow up, I will open an issue that re-thinks build time schema validation for the Markdoc Nexts.js plugin.

**Comment by jstasiak** [comment]
Hey, has this

> As a follow up, I will open an issue that re-thinks build time schema validation for the Markdoc Nexts.js plugin.

ever materialized? I'm interested in it.
