### ISSUE TITLE
Incremental build support 

### ISSUE THREAD

**Issue by altosaar** [markdoc/markdoc#297]
### What happened?

I’m trying to use this https://stackoverflow.com/questions/64189754/deploy-large-artifect-for-static-site -  but not sure how whether markdoc supports this — wasn’t sure where to ask, sorry if this is the wrong place! 

I think it should because https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration runs on nextjs and incremental static regeneration in response to a HTTP request should work.

the current architecture for https://Payless.health is to:
- take one of the hospital price lists from our data bounty (https://www.dolthub.com/repositories/onefact/paylesshealth)
- convert this into markdoc format 
- Return the result according to the page name (name of hospital, type of procedure/medication, data on file being the price!)
- Return this using vector search 

the issue is there are trillions of prices (7000 hospitals in the country, each one has different procedures, medications, treatments, and each one of the thousands of doctors at a hospital can negotiate a different price with any one of dozens of insurers. Every price needs a static page from markdoc!)

sorry if I’m not being clear, can do my best to edit and reframe! 

### To reproduce

https://stackoverflow.com/questions/64189754/deploy-large-artifect-for-static-site

### Version

Latest

### Additional context

Working at a nonprofit. Scaling markdoc to billions of pages for Payless.health.

**Comment by adreyfus-stripe** [comment]
Hi @altosaar ! Markdoc should be able to help since it's easy enough to programmatically generate files, but how you serve each static page is dependent on what you want the end user experience to look like. Your questions go a bit beyond this library since they're related to building a full content management system and less about parser/rendering component of Markdoc so it's hard for us to advise here. 

I'll close this as an issue for now since there's no blocking issue at the moment, but if you want to continue the conversation feel free to start a new discussion thread. Thanks for trying out Markdoc!
