### ISSUE TITLE
Prevent wrapping of nodes in HTML paragraphs

### ISSUE THREAD

**Issue by DanielBalog86** [markdoc/markdoc#303]
I've been trying out markdoc and I noticed that when I write an image node, it will get wrapped in a `<p>`, which can be a bit problematic when trying to customise it. 

Is there any way to disable this automatic wrapping of certain nodes? I can't immediately find anything about this in the documentation. 

One workaround seems to be to use tags instead, but I would like to avoid this as much as possible as I want to write regular markdown as much as possible. Especially for the basic stuff like images and headers I don't want to have to create a custom tag.

**Comment by rpaul-stripe** [comment]
Yes, this is unfortunate. In the CommonMark specification, images are technically inline elements. When an inline element is placed on a line by itself, it's treated as though it is enclosed in an implicit paragraph block. In the CommonMark spec, you can see in the test cases that an image on a line by itself is rendered inside of a paragraph: https://spec.commonmark.org/0.30/#example-571

We're planning to add an option to override that behavior specifically for image tags, so that an image tag on a line by itself can be treated as a block element. That is tracked in issue #156, so I think I'm going to close this for now. If there are other node types where you are finding that implicit paragraph blocks are problematic, I'm open to discussing further.

For now, you can probably use an AST transform to address this. This is a very quick and dirty example that shows how to programmatically replace a paragraph node that only contains an image with the image itself:

```
const doc = Markdoc.parse(content);
for (let node of doc.walk()) {
  if (node.type !== 'paragraph') continue;
  const interior = node.children[0].children;
  if (interior.length != 1 || interior[0].type !== 'image') continue;
  Object.assign(node, interior[0]);
}
```
