### ISSUE TITLE
Extract raw text including whitespace from tag

### ISSUE THREAD

**Issue by ReeceHumphreys** [markdoc/markdoc#327]
### What happened?

With MarkDoc and MarkDoc NextJs plugins, it seems impossible to extract the raw text of the contents of a tag while preserving indentation as the location character is always `undefined.` Additionally, it appears that the location of each paragraph tag is set to the same value, which is based on the lines of the parent tag.

It seems possible to extract each line of content in a tag by iterating through each paragraph node in the transform function. However, the content already has the whitespace trimmed, and the location does not contain the necessary information to compute the indentation level.

### To reproduce

```
...
{% foo %}
Line one
    Line two
        Line three
{% /foo %}
...
```

### Version

0.2.2

### Additional context

There may be a better way for me to extract the raw content including indentation rather than iterating through all of the paragraph nodes that may be the solution to what I need. If so I would be more than happy to go with that approach.

**Comment by segphault** [comment]
You are correct—the parser does not preserve indentation and it does not capture the character offset for text nodes. The lack of character offsets is a limitation of the underlying Markdown parser that we use to tokenize the content, and we may address this in the future. The indentation isn't preserved because paragraph indentation isn't syntactically relevant in Markdown.

We have considered the possibility of capturing the raw source text nested inside of a tag and exposing this as an attribute on the tag itself. You can actually do this yourself today by getting the line number of the opening and closing tags and slicing those lines out of the original source document. This doesn't prevent Markdoc from parsing the interior content as Markdoc, however.

We generally don't think it's a good idea to treat the content inside of Markdoc tags as literal text or use your own custom syntax and non-Markdown formatting inside of Markdoc tags. If you need to treat the content as literal text, you are probably better off using a fenced code block.

Would you mind describing your use case?

**Comment by ReeceHumphreys** [comment]
Yes I think the fenced code block approach would make the most sense! I was implementing a diagram tag that would render a Mermaid diagram. However, I ran into problems with some mermaid diagrams being indentation sensitive.

Thanks for the guidance!
