### ISSUE TITLE
Start numbers of ordered lists are ignored

### ISSUE THREAD

**Issue by emmatown** [markdoc/markdoc#371]
### What happened?

From https://spec.commonmark.org/0.30/#start-number:

> The [start number](https://spec.commonmark.org/0.30/#start-number) of an [ordered list](https://spec.commonmark.org/0.30/#ordered-list) is determined by the list number of its initial list item.

Markdoc currently ignores the start number. I'm assuming this isn't intentional since it isn't mentioned in https://markdoc.dev/docs/faq#is-markdoc-compliant-with-the-commonmark-specification.

### To reproduce

For a Markdoc document like this:

```md
2. something
```

I would have expected the AST to include the start number and the default rendered html to look like this:

```html
<article>
  <ol start="2">
    <li>something</li>
  </ol>
</article>
```

Currently it looks like this:

```html
<article>
  <ol>
    <li>something</li>
  </ol>
</article>
```

### Version

0.2.2

**Comment by rpaul-stripe** [comment]
Thanks for raising this!

It looks like markdown-it captures the number of each list item in the `info` property (apparently [added in 2021](https://github.com/markdown-it/markdown-it/commit/8bcc82aa74164a5e13a104f433c26671a92ed872)), so I can update the parser to expose this to the AST.

For the default schema, I can make it so that the ordered `list` node walks the tree looking for the first list item and then uses its number for the `start` attribute. I'll probably also need to look at the formatter to see if we can incorporate it there.
